# Output 输出
resolution = [2560, 1600]
fps = 120
sampleCount = 8
hardwareAccel = false
hevc = true
mpeg4 = false
# customEncoder = ""
fileNameFormat = "%date% %time% %info.name%_%level_prefix%"
ffmpegPreset = "medium p4 medium balanced" # "cpu nvenc qsv amf" or "any"
dynamicBitrateControl = true
bitrate = "26"
endingLength = 10.0
renderStartTime = 0.0
# renderEndTime = 
renderLoading = true


# Player 玩家
# playerAvatar = ""
playerName = "Phi Recorder"
playerRks = 16.94
challengeColor = "rainbow" # white green blue red golden rainbow
challengeRank = 51


# Graphics 图像
# res_pack_path = ""
chartDebugLine = 0.0
chartDebugNote = 0.0
chartRatio = 1.0
noteScale = 1.0

renderLine = true
renderLineExtra = true
renderNote = true
doubleHint = true
renderUiPause = true
renderUiName = true
renderUiLevel = true
renderUiScore = true
renderUiCombo = true
renderUiBar = true
renderBg = true
renderBgDim = true
particle = true
renderExtra = true

aggressive = false
roman = false
chinese = false

bgBlurriness = 80.0
watermark = "PRLite [AUTO] - Recorded by 9RayAlkalin"
combo = "RECORD"
maxParticles = 5000 # 5000 25000 200000

# Audio 音频
forceLimit = true
hires = false
loudnessEqualization = false
AudioMixOptimization = true

volumeMusic = 0.5
volumeSfx = 0.4
limitThreshold = 0.5 # if forceLimit
compressionRatio = 20.0 # else


# Other 其他
allGood = false
allBad = false
judgeOffset = 0.0
difficulty = ""
fade = 0.0
alphaTint = false

fxaa = false
speed = 1.0
